// Code generated by "stringer -type Stat -trimprefix Stat"; DO NOT EDIT.

package influxdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatStrLiteralNewline-0]
	_ = x[StatBackslashN-1]
	_ = x[StatBackslashR-2]
	_ = x[StatBackslashT-3]
	_ = x[StatBackslashF-4]
	_ = x[StatBackslashBackslash-5]
	_ = x[StatNonPrintable-6]
	_ = x[StatMeasurementEquals-7]
	_ = x[StatDoubleBackslashSeparator-8]
	_ = x[StatQuoteAtStart-9]
	_ = x[StatStrBackslashN-10]
	_ = x[StatStrBackslashR-11]
	_ = x[StatStrBackslashT-12]
	_ = x[StatStrBackslashF-13]
	_ = x[StatWhitespaceTab-14]
	_ = x[StatWhitespaceCR-15]
	_ = x[StatWhitespaceFF-16]
	_ = x[StatUnknownFieldType-17]
	_ = x[StatComment-18]
	_ = x[NumStat-19]
}

const _Stat_name = "StrLiteralNewlineBackslashNBackslashRBackslashTBackslashFBackslashBackslashNonPrintableMeasurementEqualsDoubleBackslashSeparatorQuoteAtStartStrBackslashNStrBackslashRStrBackslashTStrBackslashFWhitespaceTabWhitespaceCRWhitespaceFFUnknownFieldTypeCommentNumStat"

var _Stat_index = [...]uint16{0, 17, 27, 37, 47, 57, 75, 87, 104, 128, 140, 153, 166, 179, 192, 205, 217, 229, 245, 252, 259}

func (i Stat) String() string {
	if i >= Stat(len(_Stat_index)-1) {
		return "Stat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stat_name[_Stat_index[i]:_Stat_index[i+1]]
}
